# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
# title: 善积跬步 方以千里
# subtitle:
# description:
# keywords:
# author: dongzl
# language: zh-CN
# timezone:

# # URL
# ## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://dongzl.github.io
root: /
permalink: :year/:month/:day/:title/
# permalink_defaults:

# # Directory
# source_dir: source
# public_dir: public
# tag_dir: tags
# archive_dir: archives
# category_dir: categories
# code_dir: downloads/code
# i18n_dir: :lang
# skip_render:

# # Writing
# # new_post_name: :year/:title.md # File name of new posts
new_post_name: :year/:title.md # File name of new posts
# default_layout: post
# titlecase: false # Transform title into titlecase
# external_link: true # Open external links in new tab
# filename_case: 0
# render_drafts: false
post_asset_folder: true
# relative_link: false
# future: true
# highlight:
#   enable: true
#   line_number: true
#   auto_detect: false
#   tab_replace:
  
# # Home page setting
# # path: Root path for your blogs index page. (default = '')
# # per_page: Posts displayed per page. (0 = disable pagination)
# # order_by: Posts order. (Order by date descending by default)
# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date
  
# # Category & Tag
# default_category: uncategorized
# category_map:
# tag_map:

# # Date / Time format
# ## Hexo uses Moment.js to parse and display date
# ## You can customize the date format as defined in
# ## http://momentjs.com/docs/#/displaying/format/
# date_format: YYYY-MM-DD
# time_format: HH:mm:ss

# # Pagination
# ## Set per_page to 0 to disable pagination
per_page: 12
#pagination_dir: page

# # Extensions
# ## Plugins: https://hexo.io/plugins/
# ## Themes: https://hexo.io/themes/
# #theme: concise
# #theme: replica
# #theme: yilia
theme: hexo-theme-skapp

menu:
  home: / 
  archive: /archives
  about: /about

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/dongzl/dongzl.github.io.git
  branch: master

# math:
#   engine: 'mathjax'
#   mathjax:
#     src: 'https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
#     config:
#       tex2jax:
#         inlineMath:
#           - - '$'
#             - '$'
#           - - '\\('
#             - '\\)'
#         processEscapes: true
#       TeX:
#         equationNumbers:
#           autoNumber: 'AMS'

# Site
# blog's title
title: 董宗磊的博客

language: zh-cn

# subtitle in the banner header
subtitle: 董宗磊的博客--靡不有初，鲜克有终

# introduction  in the banner header
subtitle_desc: 取法乎上，得乎其中；取法乎中，得乎其下；取法呼下，无所得矣。

# seo keyword
keywords: 程序员, java, web, 数据库, 架构, 设计模式, 数据结构, 算法

# blog description（for seo）
description: 取法于上，仅得为中；取法于中，故为其下。

# self introduction
introduction: 不思量，自难忘！

# your blog favicon icon, support two ways: local and online. the local way need you to put the icon under  themes/hexo-theme-skapp/source/img directory
favicon_ico: /img/theme/favicon.ico

# blog logo icon in the upper left corner. support the local way and online way. 
logo: /img/theme/title.png

# avatar
avatar: /img/theme/qrcode.jpg #http://oo12ugek5.bkt.clouddn.com/images/qrcode.png
# qrcode: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png

# page default cover
default_cover: /img/theme/blog_work.png

# header background picture
header_cover: /img/theme/banner.jpeg
#http://imgblog.mrdear.cn/21312%20%281%29.jpg

# 404 page background picture
error_page_bg: /img/theme/dogs.jpg

# page loading icon
loader_img: /img/theme/loading.gif

# Baidu statistic
baidu_statistic: e4027971a230b210f4671f485b33846a

# Busuanzi
busuanzi: true

# author information
author:
  name: 董宗磊
  link: https://github.com/dongzl

# Links:
links:
  - svg: ./source/svg/github.svg
    url: https://github.com/dongzl
  - svg: ./source/svg/more.svg
    url: http://weibo.com/sanonz
  - svg: ./source/svg/twitter.svg
    url: https://twitter.com/sanonze

# footer information
about:
  info: 本站是基于 Hexo 搭建的静态资源博客，主要用于分享日常学习、生活及工作的一些心得总结，欢迎点击右下角订阅 rss。
  address: Beijing, China
  email: dongzonglei@apache.org

# Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

# Sitemap
sitemap:
  path: sitemap.xml

# Gitalk
gitTalk:
  clientId: 791785cb3bf7b9b5f1ea
  clientSecret: a73d2380b7dba08575e0190989ef017e480c20c9
  repo: dongzl.github.io
  owner: dongzl
  admin: 
    - dongzl

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-haruto
  display:
    position: left
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 1.0